---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "npm"
    directory: "/client"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/client/src-tauri"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/server"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
