---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "gomod"
    directory: "/client"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/server"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/types"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
